//! Help-text layout: the one place a description becomes terminal lines.
//!
//! Two callers render option/argument rows, and they must not drift:
//!
//! - `fdl <cmd> --help`, from a schema (see [`crate::run`]).
//! - `<binary> --help`, from the code generated by `#[derive(FdlArgs)]`.
//!
//! The derive used to push each description onto one unwrapped line while
//! `fdl` wrapped the same text properly, so the same option read differently
//! depending on which entry point printed it. Two renderers for one format is
//! the shape of defect that made the `--fdl-schema` probe fail silently for
//! days; this module exists so there is only one.
//!
//! # Description format
//!
//! A description arrives in the block form
//! `flodl_cli_macros::extract_doc` produces: blocks separated by `\n`, a block
//! starting with `- ` being a list item. Within a block, line breaks carry no
//! meaning (the text is re-wrapped to the terminal). Inline `` `code` `` and
//! `*emphasis*` spans are consumed into styling rather than printed as
//! punctuation.
//!
//! A plain single-paragraph description (no newlines, no markup) renders
//! exactly as it always did, so nothing about the common case changed.

use crate::style;

/// Label-column width for the `Arguments` section (chars, after the
/// section's own left indent). Descriptions wrap into the column to the
/// right of this.
pub const ARG_COL: usize = 22;
/// Label-column width for the `Options` section (option flags run wider
/// than positional args, so they get a roomier column).
pub const OPT_COL: usize = 30;
/// Label-column width used by the derive's generated help, which indents
/// rows by 4 and has historically aligned descriptions at column 36.
pub const DERIVE_COL: usize = 32;

/// A word/segment for description wrapping: `text` is the visible content
/// (what counts toward the wrap width), `styled` is what actually gets
/// printed (may carry ANSI escapes, which have zero visible width).
#[derive(Debug, Clone)]
pub struct Seg {
    text: String,
    styled: String,
}

impl Seg {
    pub fn plain(s: &str) -> Seg {
        Seg {
            text: s.to_string(),
            styled: s.to_string(),
        }
    }
    pub fn dim(s: &str) -> Seg {
        Seg {
            text: s.to_string(),
            styled: style::dim(s),
        }
    }
    fn empty() -> Seg {
        Seg {
            text: String::new(),
            styled: String::new(),
        }
    }
    fn is_empty(&self) -> bool {
        self.text.is_empty()
    }
    fn push_plain(&mut self, s: &str) {
        self.text.push_str(s);
        self.styled.push_str(s);
    }
    /// Append a marked-up span: it counts its bare width but prints styled.
    /// Never a wrap boundary, so `` `none`, `` keeps its comma attached and a
    /// multi-word span like `` `pre - post` `` stays whole.
    ///
    /// Amber rather than bold: bold is a weight, and a weight has to compete
    /// with surrounding prose at the same colour to be seen at all — in a
    /// paragraph it read as grey emphasis and the literals did not pop. A hue
    /// separates them at a glance, and amber is the one the shared palette
    /// already carries (see [`style::amber`]).
    fn push_marked(&mut self, s: &str) {
        self.text.push_str(s);
        self.styled.push_str(&style::amber(s));
    }
}

/// One description block: a paragraph, or a list item to be marked and
/// hanging-indented.
struct Block {
    item: bool,
    segs: Vec<Seg>,
}

/// Split a block's text into wrap units, consuming `` ` `` / `*` markup.
///
/// Units are whitespace-delimited words, except that a markup span is glued
/// into the unit being built. That gluing is the point: splitting on
/// whitespace first would tear `` `pre - post` `` into three units and strand
/// the comma in `` `none`, `` as its own word.
fn segs_of(text: &str) -> Vec<Seg> {
    let mut out: Vec<Seg> = Vec::new();
    let mut cur = Seg::empty();
    let chars: Vec<char> = text.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if c.is_whitespace() {
            if !cur.is_empty() {
                out.push(std::mem::replace(&mut cur, Seg::empty()));
            }
            i += 1;
            continue;
        }
        if let Some((content, next)) = marked_span(&chars, i) {
            cur.push_marked(&content);
            i = next;
            continue;
        }
        cur.push_plain(&c.to_string());
        i += 1;
    }
    if !cur.is_empty() {
        out.push(cur);
    }
    out
}

/// Match a markup span opening at `chars[i]`, returning its bare content and
/// the index just past the closing delimiter.
///
/// Backticks are unambiguous. `*` is not — it is also a glob, a footnote
/// marker and a multiplication sign — so emphasis requires the delimiters to
/// hug non-whitespace on the inside and the span to hold no whitespace at
/// all. That keeps `*.rs` and `a * b` untouched.
fn marked_span(chars: &[char], i: usize) -> Option<(String, usize)> {
    let delim = chars[i];
    if delim != '`' && delim != '*' {
        return None;
    }
    let start = i + 1;
    if chars.get(start).is_none_or(|c| c.is_whitespace()) {
        return None;
    }
    let mut j = start;
    while j < chars.len() {
        if chars[j] == delim {
            // Non-empty, and (for `*`) whitespace-free with a non-space
            // char before the close.
            let content: String = chars[start..j].iter().collect();
            if content.is_empty() {
                return None;
            }
            if delim == '*' && content.chars().any(char::is_whitespace) {
                return None;
            }
            if chars[j - 1].is_whitespace() {
                return None;
            }
            return Some((content, j + 1));
        }
        // An unterminated backtick span must not swallow the rest of the
        // text; a newline can't appear inside a block anyway.
        if delim == '*' && chars[j].is_whitespace() {
            return None;
        }
        j += 1;
    }
    None
}

/// Parse a block-form description into blocks, placing `annotations`
/// (pre-formatted `[default: ...]` / `[possible: ...]` strings) at the end.
///
/// They join the final block when it is a paragraph, which keeps the common
/// one-paragraph row on a single line (`RNG seed. [default: 42]`), and take a
/// line of their own otherwise. Attaching them to the FIRST paragraph instead
/// looked reasonable until a description whose summary introduces a list —
/// "…which is why only growth may cut the anchor:" — got the annotations
/// wedged between the colon and the list it announced.
fn blocks_of(desc: Option<&str>, annotations: &[String]) -> Vec<Block> {
    let mut blocks: Vec<Block> = desc
        .unwrap_or("-")
        .split('\n')
        .filter(|b| !b.trim().is_empty())
        .map(|b| match b.strip_prefix("- ") {
            Some(rest) => Block {
                item: true,
                segs: segs_of(rest),
            },
            None => Block {
                item: false,
                segs: segs_of(b),
            },
        })
        .collect();
    if blocks.is_empty() {
        blocks.push(Block {
            item: false,
            segs: vec![Seg::plain("-")],
        });
    }
    if !annotations.is_empty() {
        let anns = annotations.iter().map(|a| Seg::dim(a));
        match blocks.last_mut() {
            Some(last) if !last.item => last.segs.extend(anns),
            // Trailing block is a list item: annotations get their own line
            // rather than being tacked onto a bullet.
            _ => blocks.push(Block {
                item: false,
                segs: anns.collect(),
            }),
        }
    }
    blocks
}

/// Greedily pack segments into lines no wider than `width` visible chars,
/// one space between words. A single segment wider than `width` (e.g. a
/// long unbreakable annotation) gets its own overflowing line rather than
/// being split.
pub fn wrap_segments(segs: &[Seg], width: usize) -> Vec<String> {
    let width = width.max(1);
    let mut lines: Vec<String> = Vec::new();
    let mut cur = String::new();
    let mut cur_w = 0usize;
    for seg in segs {
        let w = seg.text.chars().count();
        if cur_w == 0 {
            cur.push_str(&seg.styled);
            cur_w = w;
        } else if cur_w + 1 + w <= width {
            cur.push(' ');
            cur.push_str(&seg.styled);
            cur_w += 1 + w;
        } else {
            lines.push(std::mem::take(&mut cur));
            cur.push_str(&seg.styled);
            cur_w = w;
        }
    }
    if !cur.is_empty() {
        lines.push(cur);
    }
    if lines.is_empty() {
        lines.push(String::new());
    }
    lines
}

/// Render a description's blocks as lines relative to the description
/// column: paragraphs flush, list items marked and hanging-indented so a
/// wrapped item stays visibly one item.
fn description_lines(blocks: &[Block], desc_width: usize) -> Vec<String> {
    const MARKER: &str = "- ";
    const HANG: &str = "  ";
    let mut out: Vec<String> = Vec::new();
    for b in blocks {
        if !b.item {
            out.extend(wrap_segments(&b.segs, desc_width));
            continue;
        }
        let inner = desc_width.saturating_sub(MARKER.len()).max(1);
        for (n, line) in wrap_segments(&b.segs, inner).into_iter().enumerate() {
            if n == 0 {
                out.push(format!("{}{line}", style::dim(MARKER)));
            } else {
                out.push(format!("{HANG}{line}"));
            }
        }
    }
    if out.is_empty() {
        out.push(String::new());
    }
    out
}

/// Lay out a two-column help row: a `label` of visible width
/// `label_visible` in a column `desc_col` chars wide, then the description
/// wrapped into the column to its right. `avail_width` is the printable
/// width the section has after its own left indent. Continuation lines align
/// under the description column; a label too wide for its column drops the
/// description to the next line, and so does a description that opens with a
/// list item.
///
/// Returns lines WITHOUT the section's left indent — the caller owns that.
pub fn row(
    label: &str,
    label_visible: usize,
    desc_col: usize,
    desc: Option<&str>,
    annotations: &[String],
    avail_width: usize,
) -> Vec<String> {
    // Floor so a narrow terminal still leaves a usable description column.
    const MIN_DESC: usize = 20;
    let desc_width = avail_width.saturating_sub(desc_col).max(MIN_DESC);
    let blocks = blocks_of(desc, annotations);
    let opens_with_item = blocks.first().is_some_and(|b| b.item);
    let desc_lines = description_lines(&blocks, desc_width);
    let pad = " ".repeat(desc_col);
    let mut out: Vec<String> = Vec::with_capacity(desc_lines.len() + 1);
    if label_visible < desc_col && !opens_with_item {
        let gap = " ".repeat(desc_col - label_visible);
        out.push(format!("{label}{gap}{}", desc_lines[0]));
    } else {
        // Label overflows its column (or the description opens with a
        // bullet, which must not share a row): own line, description below.
        out.push(label.to_string());
        out.push(format!("{pad}{}", desc_lines[0]));
    }
    for line in &desc_lines[1..] {
        out.push(format!("{pad}{line}"));
    }
    // Drop trailing padding (e.g. a "-" placeholder leaves a padded blank).
    for line in &mut out {
        while line.ends_with(' ') {
            line.pop();
        }
    }
    out
}

/// Wrap one paragraph of plain text to `width`, markup consumed into styling.
///
/// For the loose notes between sections, which are prose rather than rows and
/// still have to obey the terminal width.
pub fn wrap_text(text: &str, width: usize) -> Vec<String> {
    wrap_segments(&segs_of(text), width)
}

/// Wrap a block-form description with no label column: the banner at the top
/// of a `--help`, where paragraphs and lists get the full width.
///
/// Returns a newline-terminated string, blank line included, so the caller
/// can push it straight onto its output.
pub fn banner_string(desc: &str) -> String {
    let width = help_width();
    let blocks = blocks_of(Some(desc), &[]);
    let mut out = String::new();
    // Paragraphs get a blank line between them here, unlike inside an option
    // row: a banner is the longest prose in the help and its paragraphs are
    // genuinely separate points, where a row's paragraphs are already fenced
    // off by the blank line between rows.
    let mut prev: Option<bool> = None;
    for b in &blocks {
        if let Some(prev_item) = prev
            && !(prev_item && b.item)
        {
            out.push('\n');
        }
        for line in description_lines(std::slice::from_ref(b), width) {
            out.push_str(&line);
            out.push('\n');
        }
        prev = Some(b.item);
    }
    out.push('\n');
    out
}

/// [`row`], assembled into one indented, newline-terminated string.
///
/// The entry point for `#[derive(FdlArgs)]`'s generated help, which builds a
/// single `String` rather than printing line by line. Public because that
/// generated code lives in the user's crate.
pub fn row_string(
    indent: &str,
    label: &str,
    label_visible: usize,
    desc_col: usize,
    desc: Option<&str>,
    annotations: &[String],
) -> String {
    let avail = help_width().saturating_sub(indent.chars().count());
    let mut out = String::new();
    for line in row(label, label_visible, desc_col, desc, annotations, avail) {
        out.push_str(indent);
        out.push_str(&line);
        out.push('\n');
    }
    out
}

/// Rough visible width helper: styled strings wrap their visible content
/// in ANSI escapes, so we use the unstyled inputs we started from.
pub fn visible_width(s: &str) -> usize {
    strip_ansi(s).chars().count()
}

/// Printable width to wrap help output to. Precedence: an explicit
/// `COLUMNS` env var (lets CI and pipelines pin it), else the controlling
/// terminal's width when stderr is a TTY, else a readable default. Clamped
/// so ultra-wide terminals don't stretch descriptions past comfortable
/// reading length and narrow ones stay usable.
pub fn help_width() -> usize {
    const DEFAULT: usize = 100;
    const MIN: usize = 60;
    const MAX: usize = 120;
    let raw = std::env::var("COLUMNS")
        .ok()
        .and_then(|s| s.trim().parse::<usize>().ok())
        .filter(|&c| c > 0)
        .or_else(term_cols)
        .unwrap_or(DEFAULT);
    raw.clamp(MIN, MAX)
}

/// The controlling terminal's column count via `TIOCGWINSZ`, or `None`
/// when stderr is not a TTY (help is piped/redirected) or the query fails.
/// Dep-free: the minimal-deps policy precludes a terminal-size crate, so we
/// declare the one `ioctl` we need. Non-unix targets have no equivalent
/// here and fall back to the default width.
#[cfg(unix)]
fn term_cols() -> Option<usize> {
    use std::io::IsTerminal;
    use std::os::unix::io::AsRawFd;

    let stderr = std::io::stderr();
    if !stderr.is_terminal() {
        return None;
    }
    #[repr(C)]
    struct Winsize {
        row: u16,
        col: u16,
        xpixel: u16,
        ypixel: u16,
    }
    // TIOCGWINSZ request code: 0x5413 on Linux/Android (incl. WSL), the
    // packed 0x4008_7468 on the BSDs/macOS.
    #[cfg(any(target_os = "linux", target_os = "android"))]
    const TIOCGWINSZ: std::os::raw::c_ulong = 0x5413;
    #[cfg(not(any(target_os = "linux", target_os = "android")))]
    const TIOCGWINSZ: std::os::raw::c_ulong = 0x4008_7468;
    unsafe extern "C" {
        fn ioctl(
            fd: std::os::raw::c_int,
            request: std::os::raw::c_ulong,
            ...
        ) -> std::os::raw::c_int;
    }
    let mut ws = Winsize {
        row: 0,
        col: 0,
        xpixel: 0,
        ypixel: 0,
    };
    // SAFETY: `ioctl(TIOCGWINSZ, &Winsize)` writes the window size into the
    // struct; the fd is stderr, verified above to be a terminal.
    let rc = unsafe { ioctl(stderr.as_raw_fd(), TIOCGWINSZ, &mut ws as *mut Winsize) };
    (rc == 0 && ws.col > 0).then_some(ws.col as usize)
}

#[cfg(not(unix))]
fn term_cols() -> Option<usize> {
    None
}

pub fn strip_ansi(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\x1b' && chars.peek() == Some(&'[') {
            chars.next();
            for c in chars.by_ref() {
                if c.is_ascii_alphabetic() {
                    break;
                }
            }
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Visible text of a rendered line, so assertions don't depend on
    /// whether color happened to be enabled in this test process.
    fn plain(lines: &[String]) -> Vec<String> {
        lines.iter().map(|l| strip_ansi(l)).collect()
    }

    fn seg_texts(segs: &[Seg]) -> Vec<String> {
        segs.iter().map(|s| s.text.clone()).collect()
    }

    // ── inline markup ──────────────────────────────────────────────

    /// A code span is one wrap unit together with whatever punctuation
    /// touches it: splitting on whitespace first would strand the comma in
    /// `` `none`, `` as its own word, printing "none ," after a wrap.
    #[test]
    fn a_code_span_keeps_its_adjacent_punctuation() {
        let segs = segs_of("takes `none`, or `slowmo`.");
        assert_eq!(seg_texts(&segs), ["takes", "none,", "or", "slowmo."]);
    }

    /// A span holding spaces stays whole — it is one expression, not words.
    #[test]
    fn a_multi_word_code_span_stays_one_unit() {
        let segs = segs_of("the `pre - post` delta");
        assert_eq!(seg_texts(&segs), ["the", "pre - post", "delta"]);
    }

    /// Emphasis is recognised, but only in the unambiguous shape.
    #[test]
    fn emphasis_is_conservative_about_asterisks() {
        assert_eq!(
            seg_texts(&segs_of("the *decomposed* form")),
            ["the", "decomposed", "form"]
        );
        // A glob and a multiplication sign must survive verbatim.
        assert_eq!(seg_texts(&segs_of("*.rs files")), ["*.rs", "files"]);
        assert_eq!(seg_texts(&segs_of("a * b")), ["a", "*", "b"]);
        // An unterminated span is literal text, not a swallowed remainder.
        assert_eq!(
            seg_texts(&segs_of("2 * 3 and 4")),
            ["2", "*", "3", "and", "4"]
        );
    }

    /// An unterminated backtick must not eat the rest of the description.
    #[test]
    fn an_unterminated_backtick_stays_literal() {
        assert_eq!(seg_texts(&segs_of("a `b c")), ["a", "`b", "c"]);
    }

    // ── block layout ───────────────────────────────────────────────

    /// The regression the whole change targets: a list renders AS a list,
    /// one item per line, instead of as inline dashes in a run-on sentence.
    #[test]
    fn a_list_renders_as_lines_not_inline_dashes() {
        let desc = "Convergence guard selector.\n\
                    - `none`: passive baseline.\n\
                    - `level`: thresholds the divergence level.\n\
                    - `growth`: thresholds its growth rate.";
        let lines = plain(&row(
            "    --guard <VALUE>",
            19,
            OPT_COL,
            Some(desc),
            &["[default: level]".into()],
            100,
        ));
        assert!(
            lines[0].contains("Convergence guard selector."),
            "summary shares the label row: {:?}",
            lines[0]
        );
        assert!(
            lines.last().unwrap().contains("[default: level]"),
            "annotations trail the list, never interrupt it: {:?}",
            lines.last()
        );
        let items: Vec<&String> = lines.iter().filter(|l| l.contains("- ")).collect();
        assert_eq!(items.len(), 3, "one line per item: {lines:#?}");
        for l in &items {
            assert!(
                l.starts_with(&" ".repeat(OPT_COL)),
                "items align under the description column: {l:?}"
            );
        }
        assert!(!lines.iter().any(|l| l.contains(": passive baseline. -")));
    }

    /// A wrapped item hangs under its own text, so the eye can still tell
    /// where one item ends and the next begins.
    #[test]
    fn a_wrapped_list_item_hangs_under_itself() {
        let desc = "Accepts:\n- `fastest`: ElChe picks the rank with the lowest \
                    smoothed-ms-per-batch at run start, sticky thereafter.";
        let lines = plain(&row("    --p <V>", 11, OPT_COL, Some(desc), &[], 80));
        let first = lines.iter().position(|l| l.contains("- fastest")).unwrap();
        let cont = &lines[first + 1];
        assert!(
            cont.starts_with(&format!("{}  ", " ".repeat(OPT_COL))),
            "continuation indents past the marker: {cont:?}"
        );
    }

    /// A description that opens with a bullet gets its own line rather than
    /// hanging a marker off the label row.
    #[test]
    fn a_leading_item_does_not_share_the_label_row() {
        let lines = plain(&row(
            "    --x <V>",
            11,
            OPT_COL,
            Some("- one\n- two"),
            &[],
            80,
        ));
        assert_eq!(lines[0].trim_end(), "    --x <V>");
        assert!(lines[1].trim_start().starts_with("- one"));
    }

    /// The ordinary single-paragraph row is untouched: label and description
    /// on one line, annotations trailing.
    #[test]
    fn a_plain_row_is_unchanged() {
        let lines = plain(&row(
            "    --seed <N>",
            14,
            OPT_COL,
            Some("RNG seed."),
            &["[default: 42]".into()],
            100,
        ));
        assert_eq!(lines.len(), 1);
        assert!(lines[0].contains("--seed <N>"));
        assert!(lines[0].ends_with("RNG seed. [default: 42]"));
    }

    /// Annotations belong with the summary. When there is no paragraph to
    /// hold them they get their own line instead of riding a bullet.
    #[test]
    fn annotations_never_ride_a_list_item() {
        let lines = plain(&row(
            "    --x <V>",
            11,
            OPT_COL,
            Some("- one\n- two"),
            &["[possible: one, two]".into()],
            80,
        ));
        let last = lines.last().unwrap();
        assert!(last.contains("[possible: one, two]"), "{last:?}");
        assert!(
            !last.contains("- two"),
            "annotation split off the item: {last:?}"
        );
    }

    // ── column alignment (moved here with the layout) ──────────────

    #[test]
    fn row_aligns_continuation_under_description_column() {
        // desc_col 8, avail 28 → desc width 20 (the MIN_DESC floor).
        let rows = plain(&row("--x", 3, 8, Some("aaaa bbbb cccc dddd eeee"), &[], 28));
        // "aaaa bbbb cccc dddd" = 19 ≤ 20 fits; " eeee" would be 24, wraps.
        assert_eq!(rows[0], "--x     aaaa bbbb cccc dddd"); // 3 + 5 spaces = column 8
        assert_eq!(rows[1], format!("{}eeee", " ".repeat(8)));
        for r in &rows[1..] {
            assert!(r.starts_with(&" ".repeat(8)));
            assert!(!r.starts_with(&" ".repeat(9)));
        }
    }

    #[test]
    fn row_overflowing_label_drops_description_below() {
        // Label wider than the 8-char column → own line, desc aligned below.
        let rows = plain(&row("--a-very-long-flag", 18, 8, Some("desc"), &[], 40));
        assert_eq!(rows[0], "--a-very-long-flag");
        assert_eq!(rows[1], format!("{}desc", " ".repeat(8)));
    }

    #[test]
    fn help_width_honors_columns_env_within_clamp() {
        let _lock = crate::util::test_env::env_lock();
        let prev = std::env::var("COLUMNS").ok();
        // SAFETY: guarded by the process-wide env lock.
        unsafe { std::env::set_var("COLUMNS", "90") };
        assert_eq!(help_width(), 90);
        unsafe { std::env::set_var("COLUMNS", "9999") };
        assert_eq!(help_width(), 120); // clamped to MAX
        unsafe { std::env::set_var("COLUMNS", "10") };
        assert_eq!(help_width(), 60); // clamped to MIN
        match prev {
            Some(v) => unsafe { std::env::set_var("COLUMNS", v) },
            None => unsafe { std::env::remove_var("COLUMNS") },
        }
    }

    #[test]
    fn wrap_segments_packs_words_within_width() {
        let segs: Vec<Seg> = ["alpha", "beta", "gamma"]
            .iter()
            .map(|w| Seg::plain(w))
            .collect();
        // width 12: "alpha beta" (10) fits, +" gamma" (16) does not.
        assert_eq!(wrap_segments(&segs, 12), ["alpha beta", "gamma"]);
    }

    #[test]
    fn wrap_segments_gives_an_overlong_unit_its_own_line() {
        let segs = vec![Seg::plain("hi"), Seg::plain("averyveryverylongtoken")];
        assert_eq!(wrap_segments(&segs, 8), ["hi", "averyveryverylongtoken"]);
    }

    #[test]
    fn strip_ansi_removes_escapes_only() {
        assert_eq!(strip_ansi("\x1b[32mgo\x1b[0m"), "go");
        assert_eq!(strip_ansi("plain"), "plain");
    }
}
