//! PyTorch parity for `XlmRobertaForQuestionAnswering::from_pretrained`.
//!
//! Loads the fixture generated by `flodl-hf/scripts/parity_xlm_roberta_qa.py`
//! (`fdl flodl-hf parity xlm-roberta-qa`) and compares `[B, S, 2]`
//! logits against the HF Python reference.
//!
//! `_live` — pulls the multilingual SQuAD weights from the Hub. Run
//! with `fdl test-live`.

use std::path::Path;

use safetensors::SafeTensors;

use flodl::nn::Module;
use flodl::{Device, Tensor, Variable};
use flodl_hf::models::bert::build_extended_attention_mask;
use flodl_hf::models::xlm_roberta::XlmRobertaForQuestionAnswering;

const FIXTURE: &str = "tests/fixtures/xlm_roberta_qa_parity.safetensors";
const MODEL_ID: &str = "deepset/xlm-roberta-large-squad2";

// 5e-5, matching the other 24-layer checkpoints. This drifted at 6.2e-6
// when the tolerance was first set, comfortably inside 1e-5; it now sits
// at 1.335e-5 against freshly regenerated fixtures. The cause is not a
// weight or reference change but flodl's own fused SDPA core (4e9f0e6,
// 2026-07-28), which replaced the explicit
// matmul->scale->softmax->matmul chain: same math, different
// accumulation order, and the difference compounds per layer. Measured
// across the suite it scales with depth -- 1.2e-6 at 6 layers, ~6e-6 at
// 12, ~1e-5 to 1.8e-5 at 24 -- so a base-model budget was never the
// right one here. 5e-5 keeps ~3.7x margin over the empirical drift,
// the same standard the Davlan checkpoint's tolerance was set to.
const LOGITS_TOL: f32 = 5e-5;

mod parity_common;
use parity_common::{max_abs_diff, parse_f32, parse_i64, shape_i64};

#[test]
#[ignore = "network + ~2.2GB cache write"]
fn xlm_roberta_qa_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE)).unwrap_or_else(|e| {
        panic!("reading {FIXTURE}: {e} (run `fdl flodl-hf parity xlm-roberta-qa` to regenerate)")
    });
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids = st.tensor("inputs.input_ids").unwrap();
    let tt = st.tensor("inputs.token_type_ids").unwrap();
    let mk = st.tensor("inputs.attention_mask").unwrap();
    let ref_logits = st.tensor("outputs.logits").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids), &shape_i64(&ids), dev).unwrap(),
        false,
    );
    let token_type_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&tt), &shape_i64(&tt), dev).unwrap(),
        false,
    );
    let mask_flat_f32: Vec<f32> = parse_i64(&mk).iter().map(|&x| x as f32).collect();
    let mask_flat = Tensor::from_f32(&mask_flat_f32, &shape_i64(&mk), dev).unwrap();
    let attention_mask = Variable::new(build_extended_attention_mask(&mask_flat).unwrap(), false);

    let ref_data = parse_f32(&ref_logits);
    let ref_shape = shape_i64(&ref_logits);

    let head = XlmRobertaForQuestionAnswering::from_pretrained(MODEL_ID).unwrap();
    head.graph().eval();

    let out = head
        .graph()
        .forward_multi(&[input_ids, token_type_ids, attention_mask])
        .unwrap();
    assert_eq!(out.shape(), ref_shape, "logits shape mismatch");

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &ref_data);
    eprintln!("{MODEL_ID} logits max_abs_diff = {diff:.3e} (tol {LOGITS_TOL:.0e})");
    assert!(
        diff <= LOGITS_TOL,
        "qa parity: max_abs_diff = {diff:.3e} exceeds tol {LOGITS_TOL:.0e}",
    );
}
