//! The cloud-init user-data variant: an instance that boots straight
//! into `fdl join`.
//!
//! A SECRET artifact from the moment it exists (private key + admission
//! token inside), which is why it lands 0600 in the farm dir and never
//! on stdout. The systemd unit encodes the failure taxonomy end to end:
//! transient exits re-dial, permanent ones stop the loop and halt.

use std::path::Path;

use super::Door;

pub(super) fn home_of(user: &str) -> String {
    if user == "root" {
        "/root".to_string()
    } else {
        format!("/home/{user}")
    }
}

/// The cloud-init user-data: worker yml, private key, the tools the
/// declared door needs and the systemd recipe, so an instance boots
/// straight into a persistent `fdl join`. A SECRET artifact from the
/// moment it exists — it carries the key and the token — which is why
/// it lands 0600 in the farm dir and never on stdout.
///
/// The unit encodes the failure taxonomy end to end: `Restart=always`
/// re-dials transient exits, `RestartPreventExitStatus=2` stops the hot
/// loop on a permanent one, and `FailureAction=poweroff` (a `[Unit]`
/// option) then halts the instance.
///
/// **Halting is not always deprovisioning.** On providers that keep
/// billing a powered-off instance (DigitalOcean, and the AMD Developer
/// Cloud that runs on it, reserve disk/CPU/RAM/IP until the instance is
/// destroyed), the unit stops the work but not the meter. There, pair
/// it with a provider-side destroy.
///
/// What the instance is assumed to have is only a shell, systemd and
/// network: `fdl` is fetched here, and the door's own tooling with it.
/// Anything already baked into the image wins, since every step is
/// guarded by a `command -v`.
pub(super) fn render_cloud_init(
    label: &str,
    user: &str,
    door: Door,
    worker_yml: &str,
    private_key: &str,
) -> String {
    let indent = |s: &str| -> String {
        s.lines()
            .map(|l| {
                if l.is_empty() {
                    String::new()
                } else {
                    format!("      {l}")
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    };
    let home = home_of(user);

    // Packages the DECLARED door will actually reach for. Door B pulls a
    // source tree and builds it here, so it needs a compiler and the
    // transports; door A mounts the data root over sshfs, and prepare
    // classes a missing sshfs as permanent — which under this very unit
    // means exit 2 and a halt, on a box that only lacked a package.
    let mut packages: Vec<&str> = vec!["curl"];
    match door {
        Door::B => packages.extend(["build-essential", "pkg-config", "unzip", "rsync", "git"]),
        Door::A => packages.push("sshfs"),
        Door::Nologin => {}
    }
    let packages = packages
        .iter()
        .map(|p| format!("\x20 - {p}\n"))
        .collect::<String>();

    // Door B builds, so it needs a toolchain. Installed AS THE SERVICE
    // USER: cargo writes its registry cache into CARGO_HOME, so a
    // system-wide install root-owned and world-readable is a build that
    // fails on its first fetch. The unit then carries the matching PATH
    // rather than relying on a login shell it never gets.
    let (rust_step, rust_path) = match door {
        Door::B => (
            format!(
                "\x20 - [ sh, -c, \"command -v cargo >/dev/null || \
                 su -l {user} -c 'curl -fsSL https://sh.rustup.rs | \
                 sh -s -- -y --profile minimal --no-modify-path'\" ]\n"
            ),
            format!("{home}/.cargo/bin:"),
        ),
        _ => (String::new(), String::new()),
    };

    format!(
        "#cloud-config\n\
         # Farm `{label}` worker user-data — generated by `fdl join-config`.\n\
         # SECRET ARTIFACT: carries the join key and the admission token.\n\
         # On a provider that bills powered-off instances (DigitalOcean and\n\
         # the AMD Developer Cloud on top of it), the unit's poweroff stops\n\
         # the work but NOT the meter: destroy the instance to stop billing.\n\
         packages:\n{packages}\
         write_files:\n\
         \x20 - path: {home}/.ssh/flodl-join\n\
         \x20   owner: {user}:{user}\n\
         \x20   permissions: \"0600\"\n\
         \x20   defer: true\n\
         \x20   content: |\n{key}\n\
         \x20 - path: {home}/training/fdl.yml\n\
         \x20   owner: {user}:{user}\n\
         \x20   permissions: \"0644\"\n\
         \x20   defer: true\n\
         \x20   content: |\n{yml}\n\
         \x20 - path: /etc/systemd/system/flodl-join.service\n\
         \x20   permissions: \"0644\"\n\
         \x20   content: |\n\
         \x20     [Unit]\n\
         \x20     Description=flodl walk-in worker (farm {label})\n\
         \x20     After=network-online.target\n\
         \x20     Wants=network-online.target\n\
         \x20     FailureAction=poweroff\n\
         \n\
         \x20     [Service]\n\
         \x20     Type=simple\n\
         \x20     User={user}\n\
         \x20     WorkingDirectory={home}/training\n\
         \x20     Environment=PATH={rust_path}/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n\
         \x20     ExecStart=/usr/bin/env fdl join\n\
         \x20     Restart=always\n\
         \x20     RestartSec=5\n\
         \x20     RestartPreventExitStatus=2\n\
         \n\
         \x20     [Install]\n\
         \x20     WantedBy=multi-user.target\n\
         runcmd:\n\
         \x20 - [ sh, -c, \"command -v fdl >/dev/null || \
         (curl -fsSL https://flodl.dev/fdl -o /usr/local/bin/fdl && \
         chmod 0755 /usr/local/bin/fdl)\" ]\n\
         {rust_step}\
         \x20 - systemctl daemon-reload\n\
         \x20 - systemctl enable --now flodl-join.service\n",
        label = label,
        user = user,
        home = home,
        packages = packages,
        rust_step = rust_step,
        rust_path = rust_path,
        key = indent(private_key),
        yml = indent(worker_yml),
    )
}

/// The compose services this project dispatches commands through, if
/// any, from the merged config's `docker:` keys.
///
/// This is the disambiguator between the two dockerized shapes fdl runs
/// in. Inside a container, `/.dockerenv` answers. On the HOST, nothing
/// about the process says so — but a project whose commands carry
/// `docker: <service>` builds and runs THERE, so a tool this box lacks
/// may need installing in the image rather than here, and a fix aimed at
/// the host would be aimed at the wrong machine.
pub(super) fn docker_services(root: &Path, label: &str) -> Vec<String> {
    let Some(base) = crate::config::find_project_config(root) else {
        return Vec::new();
    };
    let Ok(project) = crate::config::load_project_with_env(&base, Some(label)) else {
        return Vec::new();
    };
    let mut seen: Vec<String> = Vec::new();
    for spec in project.commands.values() {
        if let Some(svc) = &spec.docker
            && !seen.contains(svc)
        {
            seen.push(svc.clone());
        }
    }
    seen
}
